# A: NumPy

## Introduction

### Jupyter Notebooks

This is a Jupyter Notebook. It comprises cells of two main types. There are markdown cells - like the one you are looking at! They contain text. They can also contain HTML markup. An alternative to using HTML markup is to use Markdown, which is a lightweight markup language. When you have finished typing into a markup cell, you can render its contents by typing `Shift+Enter`.

Code cells are the second of the two main types of cell. They are the default. To execute the code in a code cell, click on the cell and then type `Shift+Enter`.

Execute the next cell.

In [1]:
import numpy as np

From now on, whenever you see a code cell in this Notebook, make sure you execute it.

### Hints and Answers

This Notebook mixes explanation with exercises. Don't skip the exercises!

For each exercise, you can see a hint and the answer. Make a genuine effort to solve the exercise yourself before looking at the hint or the answer! Call me over if you need more explanation of anything.

To make the hints and answers available, you must execute the next code cell. (Click it, then `Shift+Enter`.)

In [2]:
%run do_install_HAs.py A_numpy_lab

To get the hint for Exercise 1, for example, create a code cell, type `hint(1)` into the cell, and then execute the cell (`Shift+Enter`). Similarly, to see the answer to Exercise 1, execute `answer(1)`.

### NumPy Arrays

In this lab, you will learn a little about NumPy. NumPy is a Python library for numerical computing. It offers lots of maths functions. But most important for us, it offers a fast data structure - **NumPy arrays**. 

NumPy arrays can be one-dimensional, two-dimensional, or have more dimensions. Many of NumPy's array operations are **vectorized**. This means that these operations apply to the whole array, instead of applying to individual elements of the array. These vectorized operations are fast because they are built on well-optimized code written in C. Using these operations, we can often write our own programs without resorting to looping through the elements. The resulting programs will typically be more concise and more efficient than corresponding programs written using Python lists. 

Of course, nothing comes for free. The size of a NumPy array is fixed at the time we create it.  If you insert into the array, then NumPy copies the contents into a larger array, which is time-consuming; similarly, deletion copies to a smaller array. Furthermore, if you avoid the array operations and instead write conventional programs (with loops and indexing), then your programs will often be slower than using Python lists.

Lots of other Python libraries use NumPy. Pandas, for example, is a library which we will use for reading in CSV files and wrangling our data. It offers several data structures, including `Series` and `DataFrames`, and these are built on top of NumPy arrays. The scikit-learn library is another example. It is a Machine Learning library. It expects its data to arrive as Pandas `DataFrames` or, especially, NumPy arrays.

## Creating one-dimensional arrays

We can convert a Python list into a NumPy array. Here is a one-dimensional array built from a list. 

In [3]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

Let's display `x` but also its data type, number of dimensions, its shape, its length and its size.

In [4]:
x

array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

In [5]:
x.dtype

dtype('int64')

Note that we did not specify the type when we created `x`. Rather, NumPy has inferred the type from the contents. It will choose the most general type needed, e.g. if the array contains a mix of ints and floats, the type will be float and all the ints will be stored as floats. If the array contains a mix of numbers and strings, the contents will all be stored as strings.

In [6]:
x.ndim

1

In [7]:
x.shape

(10,)

Note that shape is always a tuple. Hence, `x.shape` is `(10,)`, not `10`.

In [8]:
len(x)

10

In [9]:
x.size

10

The difference between `shape`, `len` and `size` will become clearer when we create a two-dimensional array later.

**Exercise 1.** Create a one-dimensional NumPy array `y` that contains the same numbers as `x` but where NumPy infers that the type is `float`. (Remember, you can see a hint or an answer by executing `hint(1)` or `answer(1)`, respectively.)

**Exercise 2.** Check your answer by displaying the type of `y`.

**Exercise 3.** Also display `y` itself.

You can change the type of an array by using the `astype` method. E.g. `x.astype(float)` will return a copy of `x` but with its contents stored as floats.

There are other ways of creating a NumPy array.  For example, we can create an array that contains only zeros.

In [13]:
z = np.zeros(5)

**Exercise 4.** Does array `z` contains integers or floats? Display its contents or display it data type to find out.

You can be explicit by specifying whether you want integers or floats. Here, we'll ask for floats.

In [15]:
z = np.zeros(5, dtype=float)

**Exercise 5.** Create an integer array `u` that contains 12 zeros.

`np.arange` is similar to Python's `range`, except that `np.arange` creates a NumPy array. `np.arange(start, stop)` gives values from `start` up to, but excluding, `stop`. The data type of the array is inferred from the datatype of `start` and `stop`.

In [17]:
v = np.arange(1, 11)

In [18]:
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In addition to `start` and `stop`, you can specify `step` - the distance between consecutive values.

**Exercise 6.** Use `np.arange` to create an array `w` that contains all even numbers from -100 to +100 inclusive. Display the contents of `w` so that you can check your answer.

`np.linspace` is an alternative to `np.arange` where you specify`num` - how many values you want, leaving NumPy to work out how big the steps are. This time, unlike `np.arange`, by default, `np.linspace` gives values from `start` to `stop` *inclusive* and, by default, the `dtype` will always be float.

For example, here we are creating an array that contains 5 floats between 0 and 1 inclusive.

In [20]:
scale = np.linspace(0, 1, num=5)

In [21]:
scale

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**Exercise 7.** Use `np.linspace` to create an integer array `evens` that contains all even numbers from -100 to +100 inclusive. Display the contents of `evens` so that you can check your answer.

## Creating two-dimensional arrays

A two-dimensional array is like a table, with rows and columns. We can create a two-dimensional NumPy array from a Python list of lists.

In [23]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

Below we display the contents of `A`. You will see that each nested list in the Python becomes a row of the two-dimensional NumPy array.

In [24]:
A

array([[2, 4, 0, 5],
       [1, 3, 2, 5],
       [0, 2, 3, 3]])

In the next cells,  we look at `A`'s data type (which has been inferred), number of dimensions, shape, length and size.

In [25]:
A.dtype

dtype('int64')

In [26]:
A.ndim

2

In [27]:
A.shape

(3, 4)

In [28]:
len(A)

3

Note that len() gives the size of the first dimension - the number of rows.

In [29]:
A.size

12

**Exercise 8.** Create a $5 \times 4$ array, `B`, containing all zeros (as floats). In other words, it should contain 5 rows and 4 columns. Use the `np.zeros` function. Instead of saying how many values you want -like we did earlier- here you specify the shape. Display the contents of `B` so that you can check your answer.

## Indexing and slicing

So that we don't have to scroll up and down to remind ourselves of its contents, let's create `x` again.

In [31]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

We can access an element in a one-dimensional array using an index - similar to Python. The indexes start at zero.

In [32]:
x[2]

7

And we can slice using a colon, as in the following examples.

In [33]:
x[:3] # Everything from position 0 up to but excluding position 3

array([2, 4, 7])

In [34]:
x[3:] # Everything from position 3 to the end

array([9, 1, 6, 3, 3, 0, 2])

In [35]:
x[2:5] # Everything from position 2 up to but excluding position 5

array([7, 9, 1])

Negative numbers in the slices also work as they do in Python.

However, there is a big but subtle difference between slicing lists in Python versus slicing arrays in NumPy.

A slice of a Python list is a *copy* of the values. If you change the contents of the slice, it doesn't change the original list.
 
But a slice of a NumPy array is a *view* onto the original array. If you change the contents of the slice, it changes the original list. 

We won't expain this any further here. But we will revisit the idea of copies versus views a bit later in this Notebook.

Turning now to two-dimensional arrays, let's create `A` again so that can see what it contains without scrolling:

In [36]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

If we want a particular element from `A`, we need to specify two indexes: first the row and then the column. If `A` were a Python list, you would specify them in separate brackets, and we can do this in NumPy also, e.g.: 

In [37]:
A[0][3] # row 0 column  3

5

But NumPy allows us to write just a single pair of brackets:

In [38]:
A[0, 3]

5

If we want a particular row, we can write just one index, e.g.:

In [39]:
A[1] # row 1

array([1, 3, 2, 5])

Extracting a particular column is usually done with the following 'trick':

In [40]:
A[:, 1] # column 1

array([4, 3, 2])

More complicated slicing is allowed - but not usually needed, e.g.

In [41]:
A[1:, 1:] # Everything starting from row 1  and starting from column 1, i.e. excluding row 0 and column 0

array([[3, 2, 5],
       [2, 3, 3]])

**Exercise 9.** Similar to the above, write an expression that would extract everything apart from the last row and last column.

## Boolean indexing and fancy indexing

NumPy arrays can be indexed in two ways that are not possible for Python lists.

In Boolean indexing, we supply a list or array of Booleans to extract those where the index is True. The list or array of Booleans must have the same shape as the original array.

Here's `x` again:

In [43]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

And here's an example of Boolean indexing. Notice the double brackets - the outer brackets are indexing, the inner brackets create the list of Booleans.

In [44]:
x[[True, False, True, False, True, False, False, False, False, False]]

array([2, 7, 1])

Fancy indexing also uses a list or array, but this time of indexes.

In [45]:
x[[1, 3, 5, 7, 9, 0, 2, 4, 6]]

array([4, 9, 6, 3, 2, 2, 7, 1, 3])

## Reshaping

The shape of `A` is $(3 \times 4)$ - 3 rows and 4 columns:

In [46]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

We can use the `reshape` method to give us the same data but with a different shape - provided the size (total number of elements) is preserved.

In [47]:
A.reshape((4, 3))

array([[2, 4, 0],
       [5, 1, 3],
       [2, 5, 0],
       [2, 3, 3]])

**Exercise 10.** Write an expression that reshapes `A` so that it becomes a one-dimensional array.

Reshaping does not give you a new copy of the data. It is a view onto the original data. Let's illustrate this point. We'll assign the reshaped array into `B`:

In [49]:
B = A.reshape((4, 3))

Now we'll change one of the elements of `B`:

In [50]:
B[1, 0] = -5

In [51]:
B

array([[ 2,  4,  0],
       [-5,  1,  3],
       [ 2,  5,  0],
       [ 2,  3,  3]])

But `B` is just a view onto `A`, so changing `B` also changed `A`:

In [52]:
A

array([[ 2,  4,  0, -5],
       [ 1,  3,  2,  5],
       [ 0,  2,  3,  3]])

To avoid this, we can make a copy of `A` and reshape the copy.

In [53]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

In [54]:
B = A.copy()
B.reshape((4, 3))

array([[2, 4, 0],
       [5, 1, 3],
       [2, 5, 0],
       [2, 3, 3]])

## Arithmetic operators

Suppose you want a function that takes in a one-dimensional Python list and returns a copy of that list with an amount added to every element. You could write a loop.

In [55]:
"""
One version:

def add_to_elements(in_list, amount):
    out_list = []
    for v in in_list:
        out_list.append(v + amount)
    return out_list

Another version, using a list comprehension:
"""

def add_to_elements(in_list, amount):
    return [v + amount for v in in_list]

In [56]:
x = [2, 4, 7, 9, 1, 6, 3, 3, 0, 2]

In [57]:
add_to_elements(x, 2)

[4, 6, 9, 11, 3, 8, 5, 5, 2, 4]

This is slow and cumbersome. Instead, if `x` is a NumPy array, 

In [58]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

we can write this:

In [59]:
x + 2

array([ 4,  6,  9, 11,  3,  8,  5,  5,  2,  4])

The + operation is applied *elementwise* - to every element. No need for our own loop. It is an example of vectorization - using an operator that applies to the whole array. 

It works with many operators (+, -, *, /, //, %, **). Here are a few examples.

In [60]:
x - 2

array([ 0,  2,  5,  7, -1,  4,  1,  1, -2,  0])

In [61]:
x * 10

array([20, 40, 70, 90, 10, 60, 30, 30,  0, 20])

In [62]:
x ** 2

array([ 4, 16, 49, 81,  1, 36,  9,  9,  0,  4])

You have a two-dimensional array?

In [63]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

No problem, it works on two-dimensional arrays as well as one-dimenional arrays. 

In [64]:
A + 2

array([[4, 6, 2, 7],
       [3, 5, 4, 7],
       [2, 4, 5, 5]])

In [65]:
2 - A

array([[ 0, -2,  2, -3],
       [ 1, -1,  0, -3],
       [ 2,  0, -1, -1]])

In [66]:
A ** 2

array([[ 4, 16,  0, 25],
       [ 1,  9,  4, 25],
       [ 0,  4,  9,  9]])

Note that in all the examples above, the result was a copy of the original. `x` and `A` remain unchanged.

In [67]:
x # You'll see it's unchanged

array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

In [68]:
A # Also unchanged

array([[2, 4, 0, 5],
       [1, 3, 2, 5],
       [0, 2, 3, 3]])

If you want to change the original, then you could use, e.g, `+=`, instead.

In [69]:
x += 2

In [70]:
x # You'll see it has changed

array([ 4,  6,  9, 11,  3,  8,  5,  5,  2,  4])

In [71]:
A **= 2

In [72]:
A # Also changed

array([[ 4, 16,  0, 25],
       [ 1,  9,  4, 25],
       [ 0,  4,  9,  9]])

## Comparison operators

In [73]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

In [74]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

Comparison operators are the operators that you use in if-statements: ==, !=, <, <=, >, >=, etc. In NumPy, these also work *elementwise*. Obviously the resulting array is an array of Booleans.

In [75]:
x >= 3

array([False,  True,  True,  True, False,  True,  True,  True, False,
       False])

In [76]:
A == 3

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False,  True,  True]])

**Exercise 11.** Write an expression that tells us which elements of `x` are even numbers.

In Python, you combine simple tests into more complex tests using `not`, `and` and `or`. These are not used in NumPy. Instead we use `~`, `&`, `|`, respectively. Furthermore, NumPy likes a lot of parentheses around the parts of these more complex expressions.

For example, let's find out which elements of `x` are less than 3 or greater than 5.

In [78]:
(x < 3) | (x > 5) 

array([ True, False,  True,  True,  True,  True, False, False,  True,
        True])

**Exercise 12.** Write an expression that creates an array of all the numbers from 1 to 100 inclusive. Then write an expression that finds out which elements of that array are divisible by both 3 and 5.

One **brilliant thing** is to combine elementwise comparison operators with Boolean indexing. Suppose we want to extract from `x` all the elements that are greater than or equal to 3. Indexing is done with square brackets, e.g. `x[]`. And in Boolean indexing, we place a list or array of Booleans inside these square brackets. But we know that `x >= 3` gives us an array of Booleans - so we can put it inside the square brackets, like so:

In [80]:
x[ x >= 3 ]

array([4, 7, 9, 6, 3, 3])

**Exercise 13.** Write an expression that extracts all the even numbers from `x`.

`np.where` is a bit like an if-statement. It takes three arguments. The first must be either a list or array of Booleans or, more usually, an elementwise comparison. The second and third are the values it chooses between, depending on the Boolean expression. 

For example, from `x`, we create a new array which contains "low" where the corresponding element of `x` is less than 5, and "high" otherwise.

In [82]:
np.where(x < 5, "low", "high")

array(['low', 'low', 'high', 'high', 'low', 'high', 'low', 'low', 'low',
       'low'], dtype='<U4')

In this next example, the new array contains elements of `x` but doubled when `x` is less than 5, and elements of `["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]` otherwise:

In [83]:
np.where(x < 5, x * 2, ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

array(['4', '8', 'c', 'd', '2', 'f', '6', '6', '0', '4'], dtype='<U21')

**Exercise 14.** Write an expression that creates an array of all the numbers from 1 to 100 inclusive. Then write an expression that contains the contents of the array, but where an element is divisible by 3, the new array contains "fizz"; where it is divisible by 5, it contains "buzz"; and where it is divisible by both it contains "fizzbuzz". 

For clarity, the first 15 elements of the answer will be: `'1', '2', 'fizz', '4', 'buzz', 'fizz', '7', '8', 'fizz', 'buzz', '11', 'fizz', '13', '14', 'fizzbuzz'`.

## Operators on pairs of arrays

We've been applying arithmetic and comparison operators to an array and a number, e.g. `x + 2`, `A ** 2`, `x >= 3`, and so on. But we can also apply these operators to *pairs* of arrays.

There is a condition: the two arrays must have the same dimensionality. For example, if they are one-dimensional, then they must have the same number of elements, like these, which both have 10 elements:

In [85]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

y = np.array([3, 5, 1, 2, 7, 10, 2, 6, 2, 2])

The result will also have ten elements.

The operators are applied *elementwise to corresponding elements*.

Here are examples:

In [86]:
x + y

array([ 5,  9,  8, 11,  8, 16,  5,  9,  2,  4])

In [87]:
x - y

array([-1, -1,  6,  7, -6, -4,  1, -3, -2,  0])

In [88]:
x ** y

array([       8,     1024,        7,       81,        1, 60466176,
              9,      729,        0,        4])

In [89]:
x > y

array([False, False,  True,  True, False, False,  True, False, False,
       False])

In [90]:
x < y

array([ True,  True, False, False,  True,  True, False,  True,  True,
       False])

The same condition applies to two-dimensional arrays: both must be $m \times n$, and the result will also be $m \times n$. That's why the following examples are OK; the arrays are both $3 \times 4$:

In [91]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

B = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])

In [92]:
A + B

array([[3, 5, 1, 6],
       [3, 5, 4, 7],
       [3, 5, 6, 6]])

In [93]:
A * B

array([[ 2,  4,  0,  5],
       [ 2,  6,  4, 10],
       [ 0,  6,  9,  9]])

In [94]:
A == B

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

## Dot product

When we have two one-dimensional arrays that have the same dimension, then there is a special operator called the **dot product**. It takes the product of corresponding elements and sums them. This means the result is just a number - so this is very unlike the operators we have just looked at, where the result had the same dimensions as the input data.

In NumPy, the `@` symbol gives the dot product, but you can instead use the `np.dot` function or the `dot` method. They all give the same result.

We'll do an example with arrays that have just 3 elements so that you can understand it more clearly:

In [95]:
u = np.array([2, 4, 7])

v = np.array([3, 5, 1])

The dot product will be $2 \times 3 + 4 \times 5 + 7 \times 1 = 6 + 20 + 7 = 33$.

In [96]:
u @ v # Here we're using the @ operator

33

In [97]:
np.dot(u, v) # Here we're using the np.dot function

33

In [98]:
u.dot(v) # Here we're using the dot method

33

## Universal functions

In [104]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

In [105]:
A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

We know that Python's `math` library contains many mathematical functions, e.g. `abs`, `exp`, `log10`, `sqrt`, ... For example, here's `sqrt`:

In [106]:
from math import sqrt

In [107]:
sqrt(9)

3.0

You apply `math` functions to a number, such as 9 above. You cannot apply them to a list of numbers. They do not work elementwise. Try it:

In [108]:
sqrt([1, 4, 9, 16]) # Will raise an exception

TypeError: must be real number, not list

For pretty much every function in Python's `math` module, NumPy has a corresponding function that can apply elementwise to individual numbers, to one-dimensional arrays, to two-dimensional arrays, and so on. Because of their wide applicability, they are sometimes called **universal functions**. We will illustrate with `numpy.sqrt`.

In [109]:
np.sqrt(9) # It works on individual numbers

3.0

In [110]:
np.sqrt(x) # It works elementwise on a one-dimensional array

array([1.41421356, 2.        , 2.64575131, 3.        , 1.        ,
       2.44948974, 1.73205081, 1.73205081, 0.        , 1.41421356])

In [111]:
np.sqrt(A) # It works elementwise on a two-dimensional array

array([[1.41421356, 2.        , 0.        , 2.23606798],
       [1.        , 1.73205081, 1.41421356, 2.23606798],
       [0.        , 1.41421356, 1.73205081, 1.73205081]])

The universal functions that we have mentioned so far (`np.abs`, `np.exp`, `np.log10`, `np.sqrt`) work on numbers and produce numbers. By contrast, `np.isnan` works through an array elementwise and, for each element, returns True or False according to whether the element is NaN or not.

## Methods

In addition to *functions*, there are also *methods*, and these apply elementwise. They include `max`, `mean`, `min`, `sum`, `std` (standard deviation), ...

In [112]:
x = np.array([2, 4, 7, 9, 1, 6, 3, 3, 0, 2])

A = np.array([[2, 4, 0, 5], [1, 3, 2, 5], [0, 2, 3, 3]])

In [113]:
x.sum()

37

In [114]:
A.sum()

30

In [115]:
x.min()

0

In [116]:
A.max()

5

In [117]:
x.mean()

3.7

In [118]:
x.std()

2.6851443164195103

If you have studied statistics, you might know the difference between the *population standard deviation* and a *sample standard deviation*. By default, NumPy assumes you are calculating a population standard deviation. If you want a sample standard deviation, then you specify something referred to as the 'delta degrees of freedom', setting it to be 1:

In [119]:
x.std(ddof=1)

2.8303906287138374

These methods (`max`, `mean`, `min`, `sum`, `std`, ...) apply elementwise. But, if you have a two-dimensional array, you can apply them separately to the rows (`axis = 0`) or the columns (`axis = 1`).

In [120]:
A.sum(axis=0) # Row 0 + row 1 + row 2 + row 3

array([ 3,  9,  5, 13])

In [121]:
A.sum(axis=1) # Column 1 + column 2 + column 3

array([11, 11,  8])

**Exercise 15.** Find out what the cumsum method does, e.g. [here](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html).

Play with the `cumsum` method on some one-dimensional NumPy arrays. 

Once you understand it, define a Python function, called `cumsumlist`, that does the same thing for regular Python lists. Test your function by applying it to some lists.

Execute the next cell to compare the run times of your function, which works on lists, with NumPy's `cumsum`, which works on arrays.

In [123]:
import time

a = np.arange(1, 1000001)

t0 = time.time()
np.cumsum(a)
print("Arrays took: {:.4f}s".format(time.time() - t0))

lst = list(range(1, 1000001))

t0 = time.time()
cumsumlist(lst)
print("Lists took: {:.4f}s".format(time.time() - t0))

Arrays took: 0.0111s
Lists took: 0.0849s


## Challenge Exercise

This Challenge Exercise is optional. Warning: it is very challenging! Even if you don't try to solve it, you might find the topic interesting and you can give yourself the simpler challenge of understanding the code that I give.

Read up about John Conway's *Game of Life*. In brief, there is a two-dimensional grid of square cells, each of which is either alive (1) or dead (0). At each step, we produce the next generation by looking at the neighbours (the surrounding eight cells) of each cell. A cell that is alive in generation $i$ remains alive in generation $i+1$ unless
- it has fewer than two live neighbours (underpopulation), or
- it has more than three live neighbours (overpopulation).
  
A cell remain dead unless
- it has exactly three live neighbours (reproduction).

This feels like the kind of thing we can implement in NumPy!

Below is a helper function, called `next_generation`. It generates the new state of the grid from the existing state. Note we must create a new grid, rather than update the existing grid, because survival is based on how the grid was in the previous generation.

In the function, you can see nested loops to visit each cell. For each cell, we slice 9 cells that contain the cell and its neighbours. We add up the numbers of 1s in these 9 cells but subtract the cell itself so that our count is for the 8 neighbours only. Then if-statements decide whether to change this cell or not.

There is a complication. Cells on the borders of the grid won't have 8 neighbours. Some will have 5, and those in the corners will have just 3. You might think we'd need extra if-statements to test for this. But I solved this problem differently. As you'll see in the `game_of_life` function that comes a bit later, I pad the grid with a border of zeros. This means that the original cells now all do have 8 neighbours. My for-loops below do not visit this extra border: see how `i` starts from 1, not 0, and goes up to `grid.shape[0] - 1`, not `grid.shape[0]`; and similarly for `j`.

In [124]:
def next_generation(grid):
    new_grid = np.copy(grid)
    for i in range(1, grid.shape[0] - 1):
        for j in range(1, grid.shape[1] - 1):
            neighbours = grid[i - 1 : i + 2, j - 1 : j + 2]
            num_live_neighbours = neighbours.sum() - grid[i, j]
            if grid[i, j] == 1 and (num_live_neighbours < 2 or num_live_neighbours > 3):
                new_grid[i, j] = 0
            elif grid[i, j] == 0 and num_live_neighbours == 3:
                new_grid[i, j] = 1
    return new_grid

The next function does the following:
- initialization: it creates the grid, inserts the starting pattern, and uses `np.pad` to add the border I mentioned earlier;
- generation: it uses a loop to create successive generations of the grid and stores them in a list as images;
- display: it turn the list of images into an animation that you can play in this Notebook.

In [125]:
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

def game_of_life(grid_shape, pattern, pattern_position, n_generations, dpi=20, anim_interval=500):
    grid = np.zeros(grid_shape)
    pattern = np.array(pattern)
    x_start, y_start = pattern_position[0], pattern_position[1]
    x_end, y_end = x_start + pattern.shape[0], y_start + pattern.shape[1]
    grid[x_start:x_end, y_start:y_end] = pattern
    grid = np.pad(grid, (1,))

    fig = plt.figure(dpi=dpi)
    plt.axis('off')

    images = []
    for i in range(n_generations):
        images.append((plt.imshow(grid, cmap="Greens"),))
        grid = next_generation(grid)

    anim = animation.ArtistAnimation(fig, images, interval=anim_interval, blit=True)
    plt.close(anim._fig)
    display(HTML(anim.to_jshtml()))

Finally, let's run it! I've done four examples for your entertainment. If you read up about the *Game of Life*, you are sure to come across other starting patterns that result in amazing behaviours.

In [126]:
blinker = [[1, 1, 1]]
game_of_life(grid_shape=(5,5), pattern=blinker, pattern_position=(2, 1), n_generations=10, dpi=40)

In [127]:
pulsar = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
          [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
game_of_life(grid_shape=(21,21), pattern=pulsar, pattern_position=(2, 2), n_generations=20, dpi=40)

In [128]:
glider = [[1, 0, 0],
          [0, 1, 1],
          [1, 1, 0]]
game_of_life(grid_shape=(20,20), pattern=glider, pattern_position=(0, 0), n_generations=80, dpi=40, anim_interval=100)

In [130]:
glider_gun = [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1],
              [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1],
              [1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
              [1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
game_of_life(grid_shape=(80,80), pattern=glider_gun, pattern_position=(8, 8), n_generations=200, dpi=40, anim_interval=5)

**Exercise 16.** The function called `next_generation` is old-style: it uses nested for-loops to visit each cell and works on each cell individually. The challenge is to rewrite that function in a vectorized way. If `next_generation` still has for-loops, you've not succeeded!